import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { api, media, account, fixture, invite, open, upload, json } from "./b2b-review-helpers";

// This validates web attestation entry with an explicit external-editor fixture.
// It does not claim an actual external editor or native PREPIX open occurred.
test("F16 web: separate conditions, full-byte delivery attestation, completion loss recovery, archive and reasoned reopen", async ({ browser, request }) => {
  test.setTimeout(360_000);
  const [owner, lead, recipient] = await Promise.all(["delivery-owner", "delivery-lead", "delivery-recipient"].map((name) => account(request, name)));
  const team = (await json(request.post(`${api}/v2/workspaces`, { headers: owner.headers, data: { name: "납품 브라우저 인수", requestKey: randomUUID() } }))).workspace.id;
  fixture("b2b-paid-test-fixture.cjs", { workspaceId: team, action: "purchase", target: "initial" });
  fixture("b2b-test-fixture.cjs", { workspaceId: team, action: "join", userId: lead.id });
  const projectId = (await json(request.post(`${api}/v2/workspaces/${team}/b2b/projects`, { headers: lead.headers, data: { requestKey: randomUUID(), name: "실제 파일 대조 납품", requiresWorkingFiles: true } }))).project.id;
  await invite(request, lead, team, projectId, recipient, "external", "reviewer");
  const root = `${api}/v2/workspaces/${team}/b2b/projects/${projectId}`, base = `/dashboard/workspaces/${team}/projects/${projectId}`;
  const L = await open(browser, lead, `${base}/files`);
  let R: Awaited<ReturnType<typeof open>> | undefined;
  try {
    await expect(L.page.getByRole("heading", { name: "프로젝트 자료", exact: true })).toBeVisible();
    await L.page.getByRole("combobox", { name: "자료 종류", exact: true }).selectOption("output");
    await upload(L.page, "cut-v1.mp4");
    await expect.poll(async () => (await json(request.get(`${root}/files`, { headers: lead.headers }))).versions.length, { timeout: 60_000 }).toBe(1);
    const video = (await json(request.get(`${root}/files`, { headers: lead.headers }))).versions[0];
    expect((await request.post(`${root}/assets/${video.assetId}/permissions`, { headers: lead.headers, data: { requestKey: randomUUID(), revision: 0, userId: recipient.id, canDownload: false, canUseForAi: false, reason: "Receives final delivery" } })).status()).toBe(201);
    await expect.poll(async () => (await json(request.get(`${root}/review-previews?versionId=${video.id}`, { headers: lead.headers }))).preview.state, { timeout: 120_000 }).toBe("ready");
    const made = await json(request.post(`${root}/reviews`, { headers: lead.headers, data: { requestKey: randomUUID(), title: "납품 최종 영상", versionId: video.id, audienceUserIds: [recipient.id], approverUserId: recipient.id } }));
    const review = await json(request.get(`${root}/reviews/${made.review.id}`, { headers: recipient.headers }));
    expect((await request.post(`${root}/reviews/${made.review.id}/decisions`, { headers: recipient.headers, data: { requestKey: randomUUID(), revision: review.review.revision, round: 1, versionId: video.id, decision: "approved", reason: "" } })).status()).toBe(201);
    await L.page.goto(`${base}/delivery`);
    await expect(L.page.getByRole("heading", { name: "납품 확인과 프로젝트 완료", exact: true })).toBeVisible();
    await L.page.getByLabel("최종 영상 버전", { exact: true }).selectOption(video.id);
    await expect(L.page.getByRole("row").filter({ hasText: "최종 영상 승인" })).toContainText("충족");
    await expect(L.page.getByRole("row").filter({ hasText: "편집 자료 전달" })).toContainText("확인 필요");
    await expect(L.page.getByRole("button", { name: "프로젝트 완료", exact: true })).toBeDisabled();
    await L.page.getByLabel("편집 도구", { exact: true }).selectOption("external");
    const editing = { name: "local-fixture.project", mimeType: "application/octet-stream", buffer: Buffer.from("explicit local editor fixture: project and linked source") };
    const source = { name: "cut-v1.mp4", mimeType: "video/mp4", buffer: await readFile(resolve(media, "cut-v1.mp4")) };
    await L.page.getByLabel("편집 가능한 작업 파일", { exact: true }).setInputFiles(editing);
    await L.page.getByLabel("연결되는 원본 파일 전체", { exact: true }).setInputFiles(source);
    await L.page.getByLabel("길이(초)", { exact: true }).fill("6");
    await L.page.getByLabel("가로", { exact: true }).fill("320");
    await L.page.getByLabel("세로", { exact: true }).fill("180");
    await L.page.getByLabel("프레임률", { exact: true }).fill("24");
    await L.page.getByLabel("오디오 채널", { exact: true }).fill("0");
    await L.page.getByRole("checkbox", { name: "delivery-recipient", exact: true }).check();
    await L.page.getByRole("button", { name: "파일 내용 대조", exact: true }).click();
    await expect(L.page.getByText("전체 파일 내용 대조 완료 · 아직 제출되지 않았습니다", { exact: true })).toBeVisible();
    await L.page.getByRole("button", { name: "선택한 목록을 납품 제출", exact: true }).click();
    await expect(L.page.getByRole("heading", { name: "현재 납품 목록과 열기 확인", exact: true })).toBeVisible();
    const proposed = await json(request.get(`${root}/delivery`, { headers: lead.headers }));
    expect(proposed.package.items).toHaveLength(2);
    expect(proposed.receipts).toHaveLength(0);
    R = await open(browser, recipient, `${base}/delivery`);
    await expect(R.page.getByRole("heading", { name: "다른 작업 환경에서 실제 열기 확인", exact: true })).toBeVisible();
    const confirm = R.page.getByRole("button", { name: "외부 도구 열기 확인 기록 제출", exact: true });
    await expect(confirm).toBeDisabled();
    await R.page.getByLabel("실제로 연 납품 파일 전체", { exact: true }).setInputFiles([editing, { ...source, buffer: Buffer.from("wrong contents with the same filename") }]);
    await R.page.getByRole("button", { name: "받은 파일의 전체 내용 대조", exact: true }).click();
    await expect(R.page.getByText("납품 목록의 모든 파일을 선택해야 합니다. 전체 내용 또는 크기가 다른 파일은 확인할 수 없습니다.", { exact: true })).toBeVisible();
    await expect(confirm).toBeDisabled();
    await R.page.getByLabel("실제로 연 납품 파일 전체", { exact: true }).setInputFiles([editing, source]);
    await R.page.getByRole("button", { name: "받은 파일의 전체 내용 대조", exact: true }).click();
    await expect(R.page.getByText("납품 목록의 전체 파일과 일치합니다. 실제 열기 기록을 입력해 주세요.", { exact: true })).toBeVisible();
    await R.page.getByLabel("실제로 연 편집 도구", { exact: true }).fill("Explicit local fixture editor");
    await R.page.getByLabel("편집 도구 버전", { exact: true }).fill("local-fixture-v1");
    const now = new Date();
    const local = new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
    await R.page.getByLabel("실제로 연 시각(이 장치의 현지 시간)", { exact: true }).fill(local);
    await R.page.getByRole("checkbox", { name: "제출한 곳과 다른 실제 장치·작업 환경에서 편집 프로젝트와 연결된 원본 전체를 열어 사용할 수 있음을 직접 확인했습니다.", exact: true }).check();
    await confirm.click();
    await expect(R.page.getByText(/외부 편집 도구 열기 확인 기록 · Explicit local fixture editor/)).toBeVisible();
    expect((await json(request.get(`${root}/delivery`, { headers: recipient.headers }))).receipts[0].sourceKind).toBe("external_tool_attestation");
    await L.page.reload();
    await expect(L.page.getByRole("row").filter({ hasText: "편집 자료 전달" })).toContainText("충족");
    await expect(L.page.getByRole("button", { name: "프로젝트 완료", exact: true })).toBeEnabled();
    let sends = 0, lost = false;
    await L.page.route(`${root}/delivery/receipts/complete/**`, (route) => lost ? route.abort() : route.continue());
    await L.page.route(`${root}/completion`, async (route) => { sends++; lost = true; expect((await route.fetch()).status()).toBe(201); await route.abort(); });
    await L.page.getByRole("button", { name: "프로젝트 완료", exact: true }).click();
    await expect(L.page.getByText("결과 확인이 필요한 납품 변경", { exact: true })).toBeVisible();
    lost = false;
    await L.page.unroute(`${root}/completion`); await L.page.unroute(`${root}/delivery/receipts/complete/**`);
    await L.page.reload();
    await expect(L.page.getByText("결과 확인이 필요한 납품 변경", { exact: true })).toHaveCount(0);
    await expect(L.page.getByRole("button", { name: "완료한 프로젝트 보관", exact: true })).toBeVisible();
    const completed = await json(request.get(`${root}/delivery`, { headers: lead.headers }));
    expect(completed.state).toBe("completed"); expect(completed.snapshots).toHaveLength(1); expect(sends).toBe(1);
    await L.page.getByRole("button", { name: "완료한 프로젝트 보관", exact: true }).click();
    await expect(L.page.getByRole("button", { name: "보관 해제(완료 상태로)", exact: true })).toBeVisible();
    await L.page.getByRole("button", { name: "보관 해제(완료 상태로)", exact: true }).click();
    await expect(L.page.getByRole("heading", { name: "사유를 남기고 작업 재개", exact: true })).toBeVisible();
    expect((await json(request.get(`${root}/delivery`, { headers: lead.headers }))).state).toBe("completed");
    await L.page.getByLabel("재개 사유(필수)", { exact: true }).fill("최종 장면 변경 요청");
    await L.page.getByRole("checkbox", { name: "최종 영상 승인", exact: true }).check();
    await L.page.getByRole("button", { name: "선택한 항목으로 작업 재개", exact: true }).click();
    await expect(L.page.getByText(/^작업 재개 · .*최종 장면 변경 요청$/)).toBeVisible();
    const reopened = await json(request.get(`${root}/delivery`, { headers: lead.headers }));
    expect(reopened.state).toBe("in_progress"); expect(reopened.snapshots).toHaveLength(1); expect(reopened.reopens[0].reconfirm.video).toBe(true);
    await expect(L.page.getByRole("button", { name: "프로젝트 완료", exact: true })).toBeDisabled();
    await L.page.setViewportSize({ width: 390, height: 844 });
    expect(await L.page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    expect(L.errors).toEqual([]); expect(R.errors).toEqual([]);
  } finally { await Promise.all([L, ...(R ? [R] : [])].map((view) => view.close())); }
});
