import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { api, media, account, fixture, invite, open, upload, videoReady, json } from "./b2b-review-helpers";

test("P08: selected audience only, explicit publication, lost audience receipt, no revival after rejoin", async ({ browser, request }) => {
  test.setTimeout(360_000);
  expect(media, "Set B2B_E2E_MEDIA_DIR").toBeTruthy();
  const [owner, lead, producer, client] = await Promise.all(["aud-owner", "aud-lead", "aud-producer", "aud-client"].map((name) => account(request, name)));
  const team = (await json(request.post(`${api}/v2/workspaces`, { headers: owner.headers, data: { name: "선택 공개 인수", requestKey: randomUUID() } }))).workspace.id;
  fixture("b2b-paid-test-fixture.cjs", { workspaceId: team, action: "purchase", target: "initial" });
  for (const person of [lead, producer]) fixture("b2b-test-fixture.cjs", { workspaceId: team, action: "join", userId: person.id });
  const projectId = (await json(request.post(`${api}/v2/workspaces/${team}/b2b/projects`, { headers: lead.headers, data: { requestKey: randomUUID(), name: "대상 분리" } }))).project.id;
  await invite(request, lead, team, projectId, producer, "internal", "producer");
  await invite(request, lead, team, projectId, client, "external", "reviewer");
  const root = `${api}/v2/workspaces/${team}/b2b/projects/${projectId}`;
  const base = `/dashboard/workspaces/${team}/projects/${projectId}`;
  const P = await open(browser, producer, `${base}/files`);
  const L = await open(browser, lead, `${base}/reviews`);
  let C: Awaited<ReturnType<typeof open>> | undefined;
  try {
    await upload(P.page, "cut-v1.mp4");
    await expect.poll(async () => (await json(request.get(`${root}/files`, { headers: producer.headers }))).versions.length, { timeout: 60_000 }).toBe(1);
    const version = (await json(request.get(`${root}/files`, { headers: producer.headers }))).versions[0];
    expect((await request.post(`${root}/assets/${version.assetId}/permissions`, { headers: producer.headers, data: { requestKey: randomUUID(), revision: 0, userId: lead.id, canDownload: false, canUseForAi: false, reason: "Lead checks publication" } })).status()).toBe(201);
    await expect.poll(async () => (await json(request.get(`${root}/review-previews?versionId=${version.id}`, { headers: lead.headers }))).preview.state, { timeout: 120_000 }).toBe("ready");
    expect((await json(request.get(`${root}/reviews`, { headers: lead.headers }))).reviews).toHaveLength(0);
    await L.page.getByRole("button", { name: "새 검토", exact: true }).click();
    await L.page.getByLabel("검토 제목", { exact: true }).fill("지정 대상 검토");
    await L.page.getByRole("radio", { name: /cut-v1\.mp4 · V1/ }).check();
    const publish = L.page.getByRole("button", { name: "이 버전으로 검토 시작", exact: true });
    await expect(publish).toBeDisabled();
    await expect(L.page.getByLabel("선택한 검토본 재생을 확인했습니다", { exact: true })).toBeDisabled();
    await L.page.getByRole("button", { name: "공개 전 재생", exact: true }).click();
    await videoReady(L.page);
    await L.page.locator("video").evaluate((video: HTMLVideoElement) => video.play());
    await L.page.getByLabel("선택한 검토본 재생을 확인했습니다", { exact: true }).check();
    await L.page.getByRole("radio", { name: "선택한 사람만", exact: true }).check();
    await L.page.getByRole("checkbox", { name: "aud-client · 뷰어", exact: true }).check();
    await expect(publish).toBeDisabled();
    await L.page.getByRole("combobox", { name: "승인자 선택", exact: true }).selectOption(client.id);
    await publish.click();
    await expect(L.page.getByRole("heading", { name: "지정 대상 검토", exact: true })).toBeVisible();
    const reviewUrl = new URL(L.page.url()).pathname;
    const id = reviewUrl.split("/").at(-1)!;
    const initial = await json(request.get(`${root}/reviews/${id}`, { headers: lead.headers }));
    expect(initial.review.audienceConfirmed).toBe(true);
    expect(initial.audience.map((person: { userId: string }) => person.userId)).toEqual([client.id]);
    // The uploader retains original access but is outside this review audience.
    expect((await request.get(`${root}/files/${version.id}`, { headers: producer.headers })).status()).toBe(200);
    expect((await request.get(`${root}/reviews/${id}`, { headers: producer.headers })).status()).toBe(404);
    expect((await request.post(`${root}/reviews/${id}/playback`, { headers: producer.headers, data: { round: 1 } })).status()).toBe(404);
    expect((await json(request.get(`${root}/reviews`, { headers: producer.headers }))).reviews).toHaveLength(0);
    const hiddenWork = await json(request.get(`${api}/v2/workspaces/${team}/b2b/review-work`, { headers: producer.headers }));
    expect(hiddenWork.cards).toHaveLength(0);
    expect(hiddenWork.counts.approvals + hiddenWork.counts.awaiting + hiddenWork.counts.changes).toBe(0);
    C = await open(browser, client, reviewUrl);
    await videoReady(C.page);
    await C.page.getByRole("button", { name: "승인", exact: true }).click();
    await expect.poll(async () => (await json(request.get(`${root}/reviews/${id}`, { headers: lead.headers }))).approval).toBe("approved");
    await L.page.reload();
    await L.page.getByText("고급 설정", { exact: true }).click();
    const audience = L.page.getByRole("heading", { name: "검토 대상 변경", exact: true }).locator("..");
    // M4: the form starts from the current selected round, never project-wide.
    await expect(audience.getByRole("radio", { name: "선택한 사람만", exact: true })).toBeChecked({ timeout: 30_000 });
    await expect(audience.getByRole("checkbox", { name: "aud-client · 뷰어", exact: true })).toBeChecked();
    await expect(audience.getByRole("combobox", { name: "승인자 선택", exact: true })).toHaveValue(client.id);
    await audience.getByRole("checkbox", { name: "aud-client · 뷰어", exact: true }).uncheck();
    await audience.getByRole("checkbox", { name: "aud-producer · 편집자", exact: true }).check();
    await audience.getByRole("combobox", { name: "승인자 선택", exact: true }).selectOption(producer.id);
    const confirm = audience.getByRole("button", { name: "대상을 확정하고 새 회차 공개", exact: true });
    await expect(confirm).toBeDisabled();
    await audience.getByLabel("대상 변경 사유(필수)", { exact: true }).fill("내부 재검토로 전환");
    let sends = 0, lost = false;
    await L.page.route(`${root}/review-operations/audience/**`, (route) => lost ? route.abort() : route.continue());
    await L.page.route(`${root}/reviews/${id}/audience`, async (route) => {
      sends++;
      lost = true;
      expect((await route.fetch()).status()).toBe(201);
      await route.abort();
    });
    await confirm.click();
    await expect(L.page.getByText("결과 확인이 필요한 변경", { exact: true })).toBeVisible();
    lost = false;
    await L.page.unroute(`${root}/reviews/${id}/audience`);
    await L.page.unroute(`${root}/review-operations/audience/**`);
    await L.page.reload();
    await expect(L.page.getByText(/V1 · 회차 2/)).toBeVisible();
    await expect(L.page.getByText("결과 확인이 필요한 변경", { exact: true })).toHaveCount(0);
    expect(sends).toBe(1);
    const next = await json(request.get(`${root}/reviews/${id}`, { headers: lead.headers }));
    expect(next.approval).toBe("awaiting");
    expect(next.comments).toHaveLength(0);
    expect((await json(request.get(`${root}/reviews/${id}?round=1`, { headers: lead.headers }))).decisions.some((decision: { decision: string }) => decision.decision === "approved")).toBe(true);
    expect((await request.get(`${root}/reviews/${id}`, { headers: client.headers })).status()).toBe(404);
    expect((await json(request.get(`${api}/v2/workspaces/${team}/b2b/review-work`, { headers: client.headers }))).cards).toHaveLength(0);
    const project = await json(request.get(root, { headers: lead.headers }));
    expect((await request.post(`${root}/people`, { headers: lead.headers, data: { requestKey: randomUUID(), revision: project.project.revision, userId: producer.id, role: "producer", canDownload: false, remove: true, reason: "참여 종료" } })).status()).toBe(201);
    await invite(request, lead, team, projectId, producer, "internal", "producer");
    // New participation does not resurrect the old round's audience grant.
    expect((await request.get(`${root}/reviews/${id}`, { headers: producer.headers })).status()).toBe(404);
    expect((await request.post(`${root}/reviews/${id}/playback`, { headers: producer.headers, data: { round: 2 } })).status()).toBe(404);
    await L.page.setViewportSize({ width: 390, height: 844 });
    await L.page.reload();
    await expect(L.page.getByRole("heading", { name: "지정 대상 검토", exact: true })).toBeVisible();
    expect(await L.page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    for (const view of [P, L, C]) expect(view.errors).toEqual([]);
  } finally { await Promise.all([P, L, ...(C ? [C] : [])].map((view) => view.close())); }
});
